version: '3.9'

services:

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gis_api_development
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - '.env'

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - '.env'
    ports:
      - 3000:3000
    volumes:
      - .:/rails
    depends_on:
      - db
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
volumes:
  postgres_data: {}
networks:
  default:
    name: rails_default
